name: github-docker

on: 
  push: 
    branches:
      - 'main'
  release:
    types: [created]

concurrency:
  group: docker-build
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    if: github.repository == 'geodynamics/rayleigh'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LOGIN }}

      - name: set lower case repository name
        run: |
          echo "REPO_NAME_LC=${REPO_NAME,,}" >> ${GITHUB_ENV}
        env:
          REPO_NAME: '${{ github.repository }}'

      - name: Build and push Docker image for main
        if: contains(github.event_name, 'push')
        uses: docker/build-push-action@v6
        with:
          context: ./docker/rayleigh/
          cache-from: type=registry,ref=geodynamics/rayleigh-buildenv-jammy
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{env.REPO_NAME_LC}}:latest
            ${{env.REPO_NAME_LC}}:latest

      - name: Build and push Docker image for release
        if: contains(github.event_name, 'release')
        uses: docker/build-push-action@v6
        with:
          context: ./docker/rayleigh/
          cache-from: type=registry,ref=geodynamics/rayleigh-buildenv-jammy
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{env.REPO_NAME_LC}}:${{github.ref_name}}
            ${{env.REPO_NAME_LC}}:${{github.ref_name}}


      - name: Build and push TACC image for main
        if: contains(github.event_name, 'push')
        uses: docker/build-push-action@v6
        with:
          context: ./docker/rayleigh-tacc/
          cache-from: type=registry,ref=geodynamics/rayleigh-buildenv-bionic
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{env.REPO_NAME_LC}}:latest-tacc
            ${{env.REPO_NAME_LC}}:latest-tacc

      - name: Build and push TACC image for release
        if: contains(github.event_name, 'release')
        uses: docker/build-push-action@v6
        with:
          context: ./docker/rayleigh-tacc/
          cache-from: type=registry,ref=geodynamics/rayleigh-buildenv-bionic
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{env.REPO_NAME_LC}}:${{github.ref_name}}-tacc
            ${{env.REPO_NAME_LC}}:${{github.ref_name}}-tacc
